/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StandardUserEntity } from './standardUserEntity';
import { TicketEntity } from './ticketEntity';


export interface BoughtTicketEntity { 
    id?: number;
    typedTicket?: TicketEntity;
    user?: StandardUserEntity;
}

