/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrganizerEntity } from './organizerEntity';
import { LocationEntity } from './locationEntity';
import { TicketEntity } from './ticketEntity';


export interface EventEntity { 
    id?: number;
    name?: string;
    description?: string;
    category?: string;
    date?: string;
    hour?: string;
    imgUrl?: string;
    availableTickets?: number;
    soldTickets?: number;
    organizer?: OrganizerEntity;
    location?: LocationEntity;
    tickets?: Array<TicketEntity>;
}

