/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserAccountEntity } from './userAccountEntity';
import { EventEntity } from './eventEntity';


export interface OrganizerEntity { 
    id?: number;
    userAccountEntity?: UserAccountEntity;
    events?: Array<EventEntity>;
}

