/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserAccountEntity } from './userAccountEntity';
import { BoughtTicketEntity } from './boughtTicketEntity';


export interface StandardUserEntity { 
    id?: number;
    userAccountEntity?: UserAccountEntity;
    city?: string;
    county?: string;
    boughtTickets?: Array<BoughtTicketEntity>;
}

